apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-release
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      track: release
  template:
    metadata:
      labels:
        app: frontend
        track: release
    spec:
      containers:
        - name: app
          image: 'doreg.azurecr.io/frontend/release:latest'